name: mulink
description: "Multiplatform music player"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  animations: ^2.0.11
  audio_service: ^0.18.13
  audio_video_progress_bar: ^2.0.2
  fading_edge_scrollview: ^4.1.1
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_media_metadata: ^1.0.0+1
  get: ^4.6.6
  get_it: ^7.7.0
  image: ^4.1.7
  just_audio: ^0.9.37
  just_audio_media_kit: ^2.0.4
  just_audio_platform_interface: ^4.2.2
  just_audio_web: ^0.4.9
  just_audio_windows: ^0.2.1
  path: ^1.9.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/splash/
    - assets/images/icons/
    - assets/test/
    - assets/fonts/
    - secrets.env

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
